on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: My First Command
        run: echo "Привет! Твой первый pipeline успешно сработал!"

      - name: Print Server Info
        run: |
          echo "Текущее время на сервере:"
          date
          echo "Кто я в этой системе?"
          whoami
